In [2]:
# Create a list
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# Access elements using indexing
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])

# Access elements using slicing
print("Sliced List:", numbers[1:4])

# Add elements using append()
numbers.append(60)
print("After append(60):", numbers)

# Add elements using insert()
numbers.insert(2, 25)
print("After insert(2, 25):", numbers)

# Update an element
numbers[3] = 35
print("After Updating:", numbers)

# Remove an element using remove()
numbers.remove(20)
print("After remove(20):", numbers)

# Remove an element using pop()
removed = numbers.pop()
print("Popped Element:", removed)
print("After pop():", numbers)

# Sort the list
numbers.sort()
print("Sorted List:", numbers)

# Reverse the list
numbers.reverse()
print("Reversed List:", numbers)

# Find length, maximum, minimum, and sum
print("Length:", len(numbers))
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))
print("Sum:", sum(numbers))

# List comprehension to create a new list of squares
squares = [x**2 for x in numbers]
print("Squares List:", squares)

# Create a nested list
nested_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Nested List:", nested_list)

# Access elements in a nested list
print("First Row:", nested_list[0])
print("Element 5:", nested_list[1][1])
print("Last Element:", nested_list[2][2])

Original List: [10, 20, 30, 40, 50]
First Element: 10
Last Element: 50
Sliced List: [20, 30, 40]
After append(60): [10, 20, 30, 40, 50, 60]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60]
After Updating: [10, 20, 25, 35, 40, 50, 60]
After remove(20): [10, 25, 35, 40, 50, 60]
Popped Element: 60
After pop(): [10, 25, 35, 40, 50]
Sorted List: [10, 25, 35, 40, 50]
Reversed List: [50, 40, 35, 25, 10]
Length: 5
Maximum: 50
Minimum: 10
Sum: 160
Squares List: [2500, 1600, 1225, 625, 100]
Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
First Row: [1, 2, 3]
Element 5: 5
Last Element: 9


In [3]:
# Create a tuple
numbers = (10, 20, 30, 40, 50)
print("Original Tuple:", numbers)

# Access elements using indexing
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])

# Access elements using slicing
print("Sliced Tuple:", numbers[1:4])

# Find the length of the tuple
print("Length of Tuple:", len(numbers))

# Find the index of an element
print("Index of 30:", numbers.index(30))

# Tuple packing
packed = (1, 2, 3)
print("Packed Tuple:", packed)

# Tuple unpacking
a, b, c = packed
print("Unpacked Values:")
print("a =", a)
print("b =", b)
print("c =", c)

# Convert tuple to list
num_list = list(numbers)
print("Tuple converted to List:", num_list)

# Modify the list
num_list.append(60)
num_list[1] = 25
print("Modified List:", num_list)

# Convert modified list back to tuple
numbers = tuple(num_list)
print("Modified Tuple:", numbers)

Original Tuple: (10, 20, 30, 40, 50)
First Element: 10
Last Element: 50
Sliced Tuple: (20, 30, 40)
Length of Tuple: 5
Index of 30: 2
Packed Tuple: (1, 2, 3)
Unpacked Values:
a = 1
b = 2
c = 3
Tuple converted to List: [10, 20, 30, 40, 50]
Modified List: [10, 25, 30, 40, 50, 60]
Modified Tuple: (10, 25, 30, 40, 50, 60)


In [4]:
# Create a set
set1 = {10, 20, 30, 40}
print("Original Set:", set1)

# Add an element
set1.add(50)
print("After add(50):", set1)

# Update the set with multiple elements
set1.update([60, 70])
print("After update([60, 70]):", set1)

# Remove an element using remove()
set1.remove(20)
print("After remove(20):", set1)

# Remove an element using discard()
set1.discard(100)  # No error if element does not exist
print("After discard(100):", set1)

# Remove a random element using pop()
removed = set1.pop()
print("Popped Element:", removed)
print("After pop():", set1)

# Create another set
set2 = {40, 50, 60, 80}
print("Second Set:", set2)

# Union
print("Union:", set1.union(set2))

# Intersection
print("Intersection:", set1.intersection(set2))

# Difference
print("Difference (set1 - set2):", set1.difference(set2))

# Symmetric Difference
print("Symmetric Difference:", set1.symmetric_difference(set2))

# Subset and Superset
A = {1, 2}
B = {1, 2, 3, 4}

print("A is subset of B:", A.issubset(B))
print("B is superset of A:", B.issuperset(A))

# Remove duplicate values from a list using a set
numbers = [10, 20, 20, 30, 40, 40, 50]
unique_numbers = list(set(numbers))

print("Original List:", numbers)
print("List after removing duplicates:", unique_numbers)

Original Set: {40, 10, 20, 30}
After add(50): {40, 10, 50, 20, 30}
After update([60, 70]): {70, 40, 10, 50, 20, 60, 30}
After remove(20): {70, 40, 10, 50, 60, 30}
After discard(100): {70, 40, 10, 50, 60, 30}
Popped Element: 70
After pop(): {40, 10, 50, 60, 30}
Second Set: {40, 50, 80, 60}
Union: {40, 10, 80, 50, 60, 30}
Intersection: {40, 50, 60}
Difference (set1 - set2): {10, 30}
Symmetric Difference: {80, 10, 30}
A is subset of B: True
B is superset of A: True
Original List: [10, 20, 20, 30, 40, 40, 50]
List after removing duplicates: [40, 10, 50, 20, 30]


In [5]:
# Create a dictionary
student = {
    "id": 101,
    "name": "Maha",
    "age": 20
}

print("Original Dictionary:", student)

# Access values using keys
print("Name:", student["name"])
print("Age:", student["age"])

# Add a new key-value pair
student["course"] = "Python"
print("After Adding Course:", student)

# Update an existing value
student["age"] = 21
print("After Updating Age:", student)

# Remove an element using pop()
removed = student.pop("id")
print("Removed Value:", removed)
print("After pop():", student)

# Display keys, values, and items
print("Keys:", student.keys())
print("Values:", student.values())
print("Items:", student.items())

# Access values safely using get()
print("Name:", student.get("name"))
print("Phone:", student.get("phone", "Not Found"))

# Merge two dictionaries
student2 = {
    "city": "Chennai",
    "country": "India"
}

student.update(student2)
print("Merged Dictionary:", student)

# Create a nested dictionary
students = {
    "Student1": {
        "Name": "Maha",
        "Age": 21
    },
    "Student2": {
        "Name": "John",
        "Age": 22
    }
}

print("Nested Dictionary:", students)
print("Student1 Name:", students["Student1"]["Name"])

# Dictionary comprehension
squares = {x: x*x for x in range(1, 6)}
print("Dictionary Comprehension:", squares)

Original Dictionary: {'id': 101, 'name': 'Maha', 'age': 20}
Name: Maha
Age: 20
After Adding Course: {'id': 101, 'name': 'Maha', 'age': 20, 'course': 'Python'}
After Updating Age: {'id': 101, 'name': 'Maha', 'age': 21, 'course': 'Python'}
Removed Value: 101
After pop(): {'name': 'Maha', 'age': 21, 'course': 'Python'}
Keys: dict_keys(['name', 'age', 'course'])
Values: dict_values(['Maha', 21, 'Python'])
Items: dict_items([('name', 'Maha'), ('age', 21), ('course', 'Python')])
Name: Maha
Phone: Not Found
Merged Dictionary: {'name': 'Maha', 'age': 21, 'course': 'Python', 'city': 'Chennai', 'country': 'India'}
Nested Dictionary: {'Student1': {'Name': 'Maha', 'Age': 21}, 'Student2': {'Name': 'John', 'Age': 22}}
Student1 Name: Maha
Dictionary Comprehension: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [6]:
import numpy as np
import pandas as pd

# ==========================
# NUMPY BASICS
# ==========================

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Array attributes
print("\nDimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

# Indexing and Slicing
print("\nFirst Element:", arr[0])
print("Last Element:", arr[-1])
print("Sliced Array:", arr[1:4])

# Arithmetic Operations
print("\nArray + 10:", arr + 10)
print("Array * 2:", arr * 2)

# Maximum, Minimum, Sum, Mean
print("\nMaximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Reshape
arr2 = np.array([1, 2, 3, 4, 5, 6])
print("\nReshaped Array:")
print(arr2.reshape(2, 3))

# Zeros, Ones, Identity Matrix
print("\nZeros Matrix:")
print(np.zeros((2, 3)))

print("\nOnes Matrix:")
print(np.ones((2, 2)))

print("\nIdentity Matrix:")
print(np.eye(3))

# Random Numbers
print("\nRandom Numbers:")
print(np.random.randint(1, 100, 5))


# ==========================
# PANDAS BASICS
# ==========================

# Create a DataFrame
data = {
    "Name": ["Maha", "John", "David"],
    "Age": [20, 21, 22],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)

print("\nOriginal DataFrame:")
print(df)

# Display first and last rows
print("\nHead:")
print(df.head())

print("\nTail:")
print(df.tail())

# Display information
print("\nInformation:")
print(df.info())

# Statistical summary
print("\nDescription:")
print(df.describe())

# Select columns
print("\nName Column:")
print(df["Name"])

print("\nName and Marks:")
print(df[["Name", "Marks"]])

# Filter rows
print("\nStudents with Marks > 85:")
print(df[df["Marks"] > 85])

# Add a new column
df["Result"] = "Pass"

print("\nAfter Adding Result Column:")
print(df)

# Update a value
df.loc[0, "Marks"] = 95

print("\nAfter Updating Marks:")
print(df)

# Drop a column
df = df.drop("Age", axis=1)

print("\nAfter Dropping Age Column:")
print(df)

# Sort values
print("\nSorted by Marks:")
print(df.sort_values("Marks"))

# Missing values example
df.loc[1, "Marks"] = np.nan

print("\nMissing Values:")
print(df)

print("\nAfter Filling Missing Values:")
print(df.fillna(0))

Original Array:
[10 20 30 40 50]

Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64

First Element: 10
Last Element: 50
Sliced Array: [20 30 40]

Array + 10: [20 30 40 50 60]
Array * 2: [ 20  40  60  80 100]

Maximum: 50
Minimum: 10
Sum: 150
Mean: 30.0

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix:
[[1. 1.]
 [1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Numbers:
[15  6 16 21 93]

Original DataFrame:
    Name  Age  Marks
0   Maha   20     85
1   John   21     90
2  David   22     88

Head:
    Name  Age  Marks
0   Maha   20     85
1   John   21     90
2  David   22     88

Tail:
    Name  Age  Marks
0   Maha   20     85
1   John   21     90
2  David   22     88

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2 